services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "8000:8000"

volumes:
  redis-data: